---
name: "Book Cover"
guid: "82eef869-3f18-4678-968d-06efc10b60cf"
version: "2.0.0.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Fallback cover extraction for PDF and EPUB book files"
description: >
  Fallback cover provider for Jellyfin book libraries. For PDFs, extracts
  the first page via pdftoppm. For EPUBs, performs aggressive image search
  inside the archive (by name, path, or largest image) when the Bookshelf
  plugin fails. Requires poppler-utils for PDF support.
category: "Books"
owner: "GeiserX"
artifacts:
  - "Jellyfin.Plugin.PdfCover.dll"
changelog: >
  v2.0.0: Added EPUB fallback cover extraction. Searches for cover images
  by filename (cover, portada, front), path patterns, and largest-image
  heuristic. Works as safety net when Bookshelf plugin cannot find covers.
