---
name: "PDF Cover"
guid: "a1b2c3d4-e5f6-7890-abcd-ef1234567890"
version: "1.0.0.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Extracts the first page of PDF files as cover images for book libraries"
description: >
  Automatically generates cover thumbnails for PDF books and magazines
  by extracting the first page. Requires poppler-utils (pdftoppm) installed
  in the Jellyfin container.
category: "Books"
owner: "GeiserX"
artifacts:
  - "Jellyfin.Plugin.PdfCover.dll"
changelog: >
  Initial release. Supports PDF cover extraction via pdftoppm with
  configurable DPI, JPEG quality, and timeout settings.
